# Generated by Django 5.1 on 2024-09-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_nelayanentry_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NelayanEntry',
            new_name='Product',
        ),
    ]
